## Introduction to Pandas

### Series

In [58]:
import numpy as np
import pandas as pd

obj = pd.Series([4, 7, -5, 3])  # Series are 1D
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [59]:
# indexing each point with a label:
obj2 = pd.Series([4, 7, 5, -3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a    5
c   -3
dtype: int64

In [60]:
obj2["a"]  # 5
obj2[["c", "a", "d"]]

c   -3
a    5
d    4
dtype: int64

In [61]:
# numpy-like operations preserve the index-value link:
obj2[obj2 > 0]
obj2 * 2

d     8
b    14
a    10
c    -6
dtype: int64

In [62]:
# can also be treated as a dictionary:
"b" in obj2

True

In [63]:
# in fact a Series can be created from a dict:
sdata = {"Berlandia": 700000, "Araguari": 50000}
obj3 = pd.Series(sdata)
obj3

Berlandia    700000
Araguari      50000
dtype: int64

In [64]:
# and vice-versa:
obj3.to_dict()

{'Berlandia': 700000, 'Araguari': 50000}

In [65]:
# we can also pick indexes from the dict - order from index param will be respected and missing values will be replaced with NaN:
cities = ["Araguari", "Beraba", "Berlandia"]
obj4 = pd.Series(sdata, index=cities)
obj4

Araguari      50000.0
Beraba            NaN
Berlandia    700000.0
dtype: float64

In [66]:
# isna and notna can be used to detect missing data:
obj4.isna()  # same as pd.isna(obj4)
obj4.notna()

Araguari      True
Beraba       False
Berlandia     True
dtype: bool

In [67]:
# operations between series use labels to determine matching elements:
obj3 + obj4

Araguari      100000.0
Beraba             NaN
Berlandia    1400000.0
dtype: float64

### Dataframes

Can think of it as a dictionary of Series all sharing the same index

In [68]:
# most common way to initialize is from a dict of equal length lists:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [69]:
# get only first few or last few rows - useful for large dfs:
frame.head()
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [70]:
# column rearranging and adding blank columns also works just like in Series:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "non_existing"])
frame2

   year   state  pop non_existing
0  2000    Ohio  1.5          NaN
1  2001    Ohio  1.7          NaN
2  2002    Ohio  3.6          NaN
3  2001  Nevada  2.4          NaN
4  2002  Nevada  2.9          NaN
5  2003  Nevada  3.2          NaN

In [71]:
# columns can be retrieved as series:
frame2["state"]
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [72]:
# retrieving rows by position or name:
frame2.loc[1]
frame2.iloc[1]

year            2001
state           Ohio
pop              1.7
non_existing     NaN
Name: 1, dtype: object

In [73]:
# assign a scalar to a column - all rows will be changed:
frame2["debt"] = 16.5
frame2

   year   state  pop non_existing  debt
0  2000    Ohio  1.5          NaN  16.5
1  2001    Ohio  1.7          NaN  16.5
2  2002    Ohio  3.6          NaN  16.5
3  2001  Nevada  2.4          NaN  16.5
4  2002  Nevada  2.9          NaN  16.5
5  2003  Nevada  3.2          NaN  16.5

In [74]:
# assigning an array:
frame2["debt"] = np.arange(6)
# frame2["debt"] = np.arange(7) # this would raise ValueError because lengths don't match
frame2

   year   state  pop non_existing  debt
0  2000    Ohio  1.5          NaN     0
1  2001    Ohio  1.7          NaN     1
2  2002    Ohio  3.6          NaN     2
3  2001  Nevada  2.4          NaN     3
4  2002  Nevada  2.9          NaN     4
5  2003  Nevada  3.2          NaN     5

In [75]:
# assigning a Series - labels will be matched and missing will be replaced by NaN
val = pd.Series([1, 2, 3], index=[2, 4, 5])
frame2["debt"] = val
frame2

   year   state  pop non_existing  debt
0  2000    Ohio  1.5          NaN   NaN
1  2001    Ohio  1.7          NaN   NaN
2  2002    Ohio  3.6          NaN   1.0
3  2001  Nevada  2.4          NaN   NaN
4  2002  Nevada  2.9          NaN   2.0
5  2003  Nevada  3.2          NaN   3.0

In [76]:
# create and delete columns:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop non_existing  debt  eastern
0  2000    Ohio  1.5          NaN   NaN     True
1  2001    Ohio  1.7          NaN   NaN     True
2  2002    Ohio  3.6          NaN   1.0     True
3  2001  Nevada  2.4          NaN   NaN    False
4  2002  Nevada  2.9          NaN   2.0    False
5  2003  Nevada  3.2          NaN   3.0    False

In [77]:
del frame2["eastern"]
frame2

   year   state  pop non_existing  debt
0  2000    Ohio  1.5          NaN   NaN
1  2001    Ohio  1.7          NaN   NaN
2  2002    Ohio  3.6          NaN   1.0
3  2001  Nevada  2.4          NaN   NaN
4  2002  Nevada  2.9          NaN   2.0
5  2003  Nevada  3.2          NaN   3.0

In [78]:
# another common input data: nested dictionaries - inner keys will be treated as row indices
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [79]:
# can transpose just like in numpy:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [80]:
# same works for dictionaries of series:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [81]:
# we can give names to index and columns:
frame3.index.name = "year"
frame3.columns.name = "state"

frame3  # frame3.T will transpose names too

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [82]:
# can convert to ndarray:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan, nan],
       [2001, 'Ohio', 1.7, nan, nan],
       [2002, 'Ohio', 3.6, nan, 1.0],
       [2001, 'Nevada', 2.4, nan, nan],
       [2002, 'Nevada', 2.9, nan, 2.0],
       [2003, 'Nevada', 3.2, nan, 3.0]], dtype=object)

### Index objects

In [83]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [84]:
# immutable:
obj.index[1] = "d"

TypeError: Index does not support mutable operations

In [ ]:
# behaves like an array but also a fixed size set, but can have duplicates:
type(frame3.columns)  # Index
"Ohio" in frame3.columns

True

## Essential functionality

### Reindexing

In [ ]:
obj = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])  # missing values are filled with NaN
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [ ]:
# use case: interpolation/filling:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 5])
obj3

0      blue
2    purple
5    yellow
dtype: object

In [ ]:
obj3.reindex(
    np.arange(6), method="ffill"
)  # create a new series with indexes 1 to 5; will always use last value read from obj3 when reindexing

0      blue
1      blue
2    purple
3    purple
4    purple
5    yellow
dtype: object

In [ ]:
# can reindex columns too:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=["a", "c", "d"], columns=["MG", "SP", "RJ"])
frame

   MG  SP  RJ
a   0   1   2
c   3   4   5
d   6   7   8

In [ ]:
frame.reindex(columns=["PB", "MG", "RJ"])

   PB  MG  RJ
a NaN   0   2
c NaN   3   5
d NaN   6   8

In [ ]:
# can also reindex using loc:
frame.loc[["a", "d", "c"], ["RJ", "MG"]]  # will raise with PB because it's a null column

   RJ  MG
a   2   0
d   8   6
c   5   3

### Dropping entries from an axis

In [ ]:
obj = pd.Series(np.arange(5.0), index=["a", "b", "c", "d", "e"])
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
# drop returns a copy - doesn't change in place
obj.drop(["a", "b"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
# can also drop columns:
frame.drop(columns=["RJ"])

   MG  SP
a   0   1
c   3   4
d   6   7

### Indexing, selection & filtering

Essentially the same as NumPy's, but you can also use index values (not just integers)

In [ ]:
obj1 = pd.Series([1, 2, 3])

obj1[[0, 1]]
obj1.loc[[0, 1]]  # same thing

0    1
1    2
dtype: int64

In [ ]:
# when indexes are not integers, the first will work (with a warning) but the second won't:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2[[0, 1]]

C:\Users\biels\AppData\Local\Temp\ipykernel_10876\1286389828.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1]]

a    1
b    2
dtype: int64

In [ ]:
obj2.loc[[0, 1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

This is why it's recommended to always index with `loc`.

In [ ]:
# iloc will work exclusively with integers:
obj2.iloc[[0, 1]]  # get first and second items, regardless of their labels
# obj2.iloc[['a', 'b']] # throws ValueError

a    1
b    2
dtype: int64

In [87]:
# slicing with labels is also possible
obj2.loc["b":"c"]

b    7
a    5
c   -3
dtype: int64

**IMPORTANT:** For label slicing, the **endpoint is inclusive**

In [88]:
# assignment works with loc/iloc too:
obj2.loc["b":"c"] = 5
obj2

d    4
b    5
a    5
c    5
dtype: int64

In [89]:
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"],
)
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data[["two", "three"]]  # selects columns

          two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [91]:
data[:2]  # selects first two rows, all columns

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [92]:
data[data["three"] > 5]  # select all rows where the column 'three' is greater than 5

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data[data < 5]  # replaces all the falsy with NaN

          one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [94]:
data[data < 5] = 0  # assigns only to cells where the condition is true
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### loc and iloc in dataframes

In [95]:
data.loc["Colorado", "two"]  # row, column
# data.loc["Colorado", ["two", "three"]] # multiple columns from a single row (as a series)
# data.loc[["Colorado", "Ohio"], ["two", "three"]] # multiple rows and columns (as a dataframe)

np.int64(5)

In [96]:
# equivalents using iloc:
data.iloc[1, 1]
data.iloc[1, [1, 2]]
data.iloc[[1, 0], [1, 2]]

# and an extra:
data.iloc[:, :3][
    data["three"] > 5
]  # all rows, all columns except last; then filter rows where column 'three' is greater than 5

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

**IMPORTANT:** boolean arrays cannot be used with iloc

In [97]:
# there's also at and iat that will return the value at a specific row and column
data.at["Colorado", "two"]

np.int64(5)

In [98]:
# attention point when assigning with chained selections:
data.loc[data.three == 6]["three"] = 7  # won't work

C:\Users\biels\AppData\Local\Temp\ipykernel_17708\3880719736.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three == 6]["three"] = 7  # won't work

In [99]:
data.loc[data.three == 5, "three"] = 6  # works
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Arithmetic and data alignment

Both rows and columns are aligned when doing operations between two series or DFs. Non-matching indexes will be replaced in result by NaN or `fill_value`, if specified.

In [100]:
# broadcasting in numpy:
arr = np.arange(12).reshape((3, 4))
arr - arr[0]  # element-wise subtraction of arr[0] is applied to every row in arr:

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [101]:
# similarly, in pandas:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
frame

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [102]:
frame - frame.iloc[0]

        b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [103]:
series = frame.iloc[0].copy()
series["a"] = 10
series

b     0
d     1
e     2
a    10
Name: Utah, dtype: int64

In [104]:
frame - series  # column "a" will be created

         a  b  d  e
Utah   NaN  0  0  0
Ohio   NaN  3  3  3
Texas  NaN  6  6  6
Oregon NaN  9  9  9

In [105]:
# can broadcast over columns too by specifying axis argument:
frame.sub(frame["b"], axis="index")

        b  d  e
Utah    0  1  2
Ohio    0  1  2
Texas   0  1  2
Oregon  0  1  2

#### Mapping

In [106]:
# numpy ufuncs work in dfs too:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list("abc"))
np.abs(frame)

   a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [107]:
# we can apply any function to the df rows or columns using apply:
def f1(x):
    return x.max() - x.min()


frame.apply(f1)  # applies to columns
frame.apply(f1, axis="columns")  # applies to rows

0    2
1    2
2    2
3    2
dtype: int64

In [108]:
# functions applied can also return series:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])


frame.apply(f2, axis="columns")

   min  max
0    0    2
1    3    5
2    6    8
3    9   11

In [109]:
# we can apply element-wise using map:
def my_format(x):
    return f"{x:.2f}"


frame.map(my_format)

      a      b      c
0  0.00   1.00   2.00
1  3.00   4.00   5.00
2  6.00   7.00   8.00
3  9.00  10.00  11.00

#### Sorting and ranking

In [110]:
df = pd.DataFrame(np.arange(4).reshape((2, 2)), index=["d", "c"], columns=list("ba"))
df

   b  a
d  0  1
c  2  3

In [111]:
df.sort_index()  # ascending arg defines order

   b  a
c  2  3
d  0  1

In [112]:
# sort columns:
df.sort_index(axis="columns")

   a  b
d  1  0
c  3  2

In [113]:
# sort by values:
obj = pd.Series([4, 1, 2, 3, np.nan])
obj.sort_values()  # NaN position can be specified with na_position arg

1    1.0
2    2.0
3    3.0
0    4.0
4    NaN
dtype: float64

In [114]:
# can specify a column or list of columns to use for sorting:
df.sort_values("b", ascending=False)

   b  a
c  2  3
d  0  1

In [115]:
# rank returns the "position" where each cell should be when sorting:
obj.rank()  # can specify method to rank repeating values properly

0    4.0
1    1.0
2    2.0
3    3.0
4    NaN
dtype: float64

##### Axis indexes with duplicate labels

In [116]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj.index.is_unique

False

In [117]:
obj["a"]  # returns a Series with all occurrences

a    0
a    1
dtype: int64

### Summarizing and computing descriptive stats

In [118]:
df = pd.DataFrame(
    [[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=["a", "b", "c", "d"], columns=["one", "two"]
)
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [119]:
df.sum()  # sums columns, NaN is treated as 0 except if skipna argument is set to False
df.sum(axis="columns")  # sums rows

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [120]:
df.idxmin()  # the row with maximum value for each column

one    d
two    b
dtype: object

In [121]:
df.cumsum()  # an array with the cummulative sum across columns

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [124]:
df.describe()  # multiple statistics

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [123]:
# on non-numeric series
pd.Series(["a", "a", "b", "c"] * 4).describe()

count     16
unique     3
top        a
freq       8
dtype: object

#### Correlation and covariance

In [ ]:
price = pd.read_pickle("examples/yahoo_price.pkl")
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [127]:
returns = price.pct_change()
returns.tail()

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [ ]:
# calculate correlation between percentage change in MSFT and IBM:
returns["MSFT"].corr(returns["IBM"])  # values are aligned by index

np.float64(0.49976361144151155)

In [ ]:
# same for covariance
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703546e-05)

In [ ]:
# then for the whole df, as a correlation matrix:
returns.corr()

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [ ]:
# calculate correlation for each column with a separate series:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [ ]:
# calculate correlation between matching columns of two dataframes:
volume["non_existing"] = 0
returns.corrwith(volume)

AAPL           -0.075565
GOOG           -0.007067
IBM            -0.204849
MSFT           -0.092950
non_existing         NaN
dtype: float64

In [ ]:
# specifying axis="columns" calculates row by row
returns.corrwith(volume, axis="columns")

Date
2010-01-04         NaN
2010-01-05    0.737298
2010-01-06    0.017069
2010-01-07    0.507614
2010-01-08   -0.779646
                ...
2016-10-17   -0.881606
2016-10-18   -0.303369
2016-10-19   -0.970723
2016-10-20   -0.304414
2016-10-21    0.927824
Length: 1714, dtype: float64

#### Unique values, value counts, memberships

In [136]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [137]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [ ]:
mask = obj.isin(["b", "c"])
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
# indexes of a value in a array with only uniques, in another array with reps:
unique_vals = obj.unique()  # [c, a, d, b]

pd.Index(unique_vals).get_indexer(obj)

array([0, 1, 2, 1, 1, 3, 3, 0, 0])

In [147]:
# count the occurrences of each value inside each column of a df:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4], "Qu2": [2, 3, 1, 2, 3], "Qu3": [1, 5, 2, 4, 4]})
data.apply(pd.value_counts).fillna(0)

C:\Users\biels\AppData\Local\Temp\ipykernel_17708\2317489911.py:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  data.apply(pd.value_counts).fillna(0)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0